# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from appointments.grpc import appointments_pb2 as appointments_dot_grpc_dot_appointments__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class AppointmentControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/settings.appointments.AppointmentController/Create',
                request_serializer=appointments_dot_grpc_dot_appointments__pb2.AppointmentRequest.SerializeToString,
                response_deserializer=appointments_dot_grpc_dot_appointments__pb2.AppointmentResponse.FromString,
                )
        self.Destroy = channel.unary_unary(
                '/settings.appointments.AppointmentController/Destroy',
                request_serializer=appointments_dot_grpc_dot_appointments__pb2.AppointmentDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.List = channel.unary_unary(
                '/settings.appointments.AppointmentController/List',
                request_serializer=appointments_dot_grpc_dot_appointments__pb2.AppointmentListRequest.SerializeToString,
                response_deserializer=appointments_dot_grpc_dot_appointments__pb2.AppointmentListResponse.FromString,
                )
        self.PartialUpdate = channel.unary_unary(
                '/settings.appointments.AppointmentController/PartialUpdate',
                request_serializer=appointments_dot_grpc_dot_appointments__pb2.AppointmentPartialUpdateRequest.SerializeToString,
                response_deserializer=appointments_dot_grpc_dot_appointments__pb2.AppointmentResponse.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/settings.appointments.AppointmentController/Retrieve',
                request_serializer=appointments_dot_grpc_dot_appointments__pb2.AppointmentRetrieveRequest.SerializeToString,
                response_deserializer=appointments_dot_grpc_dot_appointments__pb2.AppointmentResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/settings.appointments.AppointmentController/Update',
                request_serializer=appointments_dot_grpc_dot_appointments__pb2.AppointmentRequest.SerializeToString,
                response_deserializer=appointments_dot_grpc_dot_appointments__pb2.AppointmentResponse.FromString,
                )


class AppointmentControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AppointmentControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=appointments_dot_grpc_dot_appointments__pb2.AppointmentRequest.FromString,
                    response_serializer=appointments_dot_grpc_dot_appointments__pb2.AppointmentResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=appointments_dot_grpc_dot_appointments__pb2.AppointmentDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=appointments_dot_grpc_dot_appointments__pb2.AppointmentListRequest.FromString,
                    response_serializer=appointments_dot_grpc_dot_appointments__pb2.AppointmentListResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=appointments_dot_grpc_dot_appointments__pb2.AppointmentPartialUpdateRequest.FromString,
                    response_serializer=appointments_dot_grpc_dot_appointments__pb2.AppointmentResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=appointments_dot_grpc_dot_appointments__pb2.AppointmentRetrieveRequest.FromString,
                    response_serializer=appointments_dot_grpc_dot_appointments__pb2.AppointmentResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=appointments_dot_grpc_dot_appointments__pb2.AppointmentRequest.FromString,
                    response_serializer=appointments_dot_grpc_dot_appointments__pb2.AppointmentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'settings.appointments.AppointmentController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AppointmentController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/settings.appointments.AppointmentController/Create',
            appointments_dot_grpc_dot_appointments__pb2.AppointmentRequest.SerializeToString,
            appointments_dot_grpc_dot_appointments__pb2.AppointmentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/settings.appointments.AppointmentController/Destroy',
            appointments_dot_grpc_dot_appointments__pb2.AppointmentDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/settings.appointments.AppointmentController/List',
            appointments_dot_grpc_dot_appointments__pb2.AppointmentListRequest.SerializeToString,
            appointments_dot_grpc_dot_appointments__pb2.AppointmentListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/settings.appointments.AppointmentController/PartialUpdate',
            appointments_dot_grpc_dot_appointments__pb2.AppointmentPartialUpdateRequest.SerializeToString,
            appointments_dot_grpc_dot_appointments__pb2.AppointmentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/settings.appointments.AppointmentController/Retrieve',
            appointments_dot_grpc_dot_appointments__pb2.AppointmentRetrieveRequest.SerializeToString,
            appointments_dot_grpc_dot_appointments__pb2.AppointmentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/settings.appointments.AppointmentController/Update',
            appointments_dot_grpc_dot_appointments__pb2.AppointmentRequest.SerializeToString,
            appointments_dot_grpc_dot_appointments__pb2.AppointmentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
